players_name = input("What is your name? ")
team_name = input("Which team do you play for? ")
players_position = input("Which position do you play? ")
jersey_number = input("What is your jersey number? ")
hometown = input("Which hometown do you live in? ")
print("#"*40)
print(f"       LEGENDS OF THE LEAGUE")
print("#"*40)
print()
print(f"Player:    {players_name}")
print(f"Team:      {team_name}")
print(f"Position:  {players_position}")
print(f"Number:    {jersey_number}")
print()
print("-"*40)
print(f"Player Tag: {jersey_number}-{team_name}-{players_name}")
print(f"Hometown:   {hometown}")
print("-"*40)
print("#"*40)